### ISSUE TITLE
restored backup save data, everything reset

### ISSUE THREAD

**Issue by kevincuax** [iomintz/acnh-backup-restore#2]
I tried saving my animal crossing data and restoring it, but now everything's gone.

However, based on file size comparison, it seems that data was saved properly.
<img width="872" alt="Screen Shot 2020-04-14 at 3 46 38 AM" src="https://user-images.githubusercontent.com/4261092/79216826-afa3bf80-7e02-11ea-914d-6ca81b1633ea.png">

These are the file sizes of when I first tried to save my data

<img width="684" alt="Screen Shot 2020-04-14 at 3 46 14 AM" src="https://user-images.githubusercontent.com/4261092/79216836-b4687380-7e02-11ea-951f-0f6b3cb96b8f.png">

And then these are the file saves after I tried to save my data again after restoring the backup.
So, it seems the backup failed and now all my data is gone. What might be the issue and how can i fix it?

**Comment by ioistired** [comment]
Are there no files outside of the Villager1 directory?

**Comment by kevincuax** [comment]
there are no files in the 2021-07-019 130226 directory besides villager 1. perhaps the backup files weren't made properly after all?

**Comment by ioistired** [comment]
That seems to be the case, yes. I'm really sorry about that :\

**Comment by kevincuax** [comment]
hmm, okay. yeah kinda sad about it but it's okay i'll get over it haha. i may have prematurely closed the program while saving the backup, but i don't really remember. thank you for the help though!

**Comment by ioistired** [comment]
Closing as invalid due to the possibility of user error. Always make sure it says it's done before you close the program.
